---

- hosts: web
  become: true

  pre_tasks:
    - name: install commons
      apt:
        name:
          - python3-pip
        update_cache: yes

  roles:
    - wwwuser
    - docker
    - traefik
