---
- name: apt repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

- name: install
  apt:
    name: "php{{ php_version }}-fpm"
    state: present
    update_cache: yes
    install_recommends: no

- name: install packages
  apt:
    name: "{{ php_packages | list }}"
    state: present
    install_recommends: no

- name: change default version
  alternatives:
    name: php
    path: /usr/bin/php{{ php_version }}
