---
- name: download apt key
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /tmp/php.gpg

- name: install apt key
  apt_key:
    file: /tmp/php.gpg
    state: present

- name: apt repository
  apt_repository:
    repo: deb https://packages.sury.org/php/ buster main

- name: install
  apt:
    name: "php{{ php_version }}-fpm"
    state: present
    update_cache: yes
    install_recommends: no

- name: install packages
  apt:
    name: "{{ php_packages | list }}"
    state: present
    install_recommends: no

- name: change default version
  alternatives:
    name: php
    path: /usr/bin/php{{ php_version }}
